/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RabbisRouteImport } from './routes/rabbis'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RabbisIdRouteImport } from './routes/rabbis.$id'
import { Route as ArticlesIdRouteImport } from './routes/articles.$id'
import { Route as ArticlesPerekPerekIdRouteImport } from './routes/articles.perek.$perekId'

const RabbisRoute = RabbisRouteImport.update({
  id: '/rabbis',
  path: '/rabbis',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RabbisIdRoute = RabbisIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RabbisRoute,
} as any)
const ArticlesIdRoute = ArticlesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ArticlesRoute,
} as any)
const ArticlesPerekPerekIdRoute = ArticlesPerekPerekIdRouteImport.update({
  id: '/perek/$perekId',
  path: '/perek/$perekId',
  getParentRoute: () => ArticlesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/rabbis': typeof RabbisRouteWithChildren
  '/articles/$id': typeof ArticlesIdRoute
  '/rabbis/$id': typeof RabbisIdRoute
  '/articles/perek/$perekId': typeof ArticlesPerekPerekIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/rabbis': typeof RabbisRouteWithChildren
  '/articles/$id': typeof ArticlesIdRoute
  '/rabbis/$id': typeof RabbisIdRoute
  '/articles/perek/$perekId': typeof ArticlesPerekPerekIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/rabbis': typeof RabbisRouteWithChildren
  '/articles/$id': typeof ArticlesIdRoute
  '/rabbis/$id': typeof RabbisIdRoute
  '/articles/perek/$perekId': typeof ArticlesPerekPerekIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/articles'
    | '/rabbis'
    | '/articles/$id'
    | '/rabbis/$id'
    | '/articles/perek/$perekId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/articles'
    | '/rabbis'
    | '/articles/$id'
    | '/rabbis/$id'
    | '/articles/perek/$perekId'
  id:
    | '__root__'
    | '/'
    | '/articles'
    | '/rabbis'
    | '/articles/$id'
    | '/rabbis/$id'
    | '/articles/perek/$perekId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArticlesRoute: typeof ArticlesRouteWithChildren
  RabbisRoute: typeof RabbisRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rabbis': {
      id: '/rabbis'
      path: '/rabbis'
      fullPath: '/rabbis'
      preLoaderRoute: typeof RabbisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rabbis/$id': {
      id: '/rabbis/$id'
      path: '/$id'
      fullPath: '/rabbis/$id'
      preLoaderRoute: typeof RabbisIdRouteImport
      parentRoute: typeof RabbisRoute
    }
    '/articles/$id': {
      id: '/articles/$id'
      path: '/$id'
      fullPath: '/articles/$id'
      preLoaderRoute: typeof ArticlesIdRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/perek/$perekId': {
      id: '/articles/perek/$perekId'
      path: '/perek/$perekId'
      fullPath: '/articles/perek/$perekId'
      preLoaderRoute: typeof ArticlesPerekPerekIdRouteImport
      parentRoute: typeof ArticlesRoute
    }
  }
}

interface ArticlesRouteChildren {
  ArticlesIdRoute: typeof ArticlesIdRoute
  ArticlesPerekPerekIdRoute: typeof ArticlesPerekPerekIdRoute
}

const ArticlesRouteChildren: ArticlesRouteChildren = {
  ArticlesIdRoute: ArticlesIdRoute,
  ArticlesPerekPerekIdRoute: ArticlesPerekPerekIdRoute,
}

const ArticlesRouteWithChildren = ArticlesRoute._addFileChildren(
  ArticlesRouteChildren,
)

interface RabbisRouteChildren {
  RabbisIdRoute: typeof RabbisIdRoute
}

const RabbisRouteChildren: RabbisRouteChildren = {
  RabbisIdRoute: RabbisIdRoute,
}

const RabbisRouteWithChildren =
  RabbisRoute._addFileChildren(RabbisRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArticlesRoute: ArticlesRouteWithChildren,
  RabbisRoute: RabbisRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
