# ============================================================================
# ⚠️ DISCLAIMER: This CloudFormation template has NEVER been tested or deployed.
# It is maintained as Infrastructure as Code DOCUMENTATION ONLY to reflect the
# de-facto AWS configuration. Do not assume it will work without thorough testing.
# ============================================================================

AWSTemplateFormatVersion: "2010-09-09"
Description: |
  CloudWatch Log Groups and Auto Scaling for Bible On Site project.

  ⚠️ WARNING: This template is DOCUMENTATION ONLY and has never been deployed.

  This template documents the CloudWatch Logs configuration for ECS container logs,
  Application Auto Scaling, Container Insights, SNS alerting, and deployment alarms.

  CONTAINER INSIGHTS:
  Enabled on bible-on-site-cluster. Publishes ECS/ContainerInsights metrics:
  RunningTaskCount, DesiredTaskCount, TaskSetFailedTaskCount, CPU/MemoryUtilization, etc.

  LOG GROUPS:
  | Log Group Name | Retention | Purpose |
  |----------------|-----------|---------|
  | /ecs/bible-on-site-website | 180 days | ECS Website container logs |

  Log streams are created automatically by ECS with the pattern:
  ecs/<container-name>/<task-id>

  AUTO SCALING (bible-on-site-website): Min 1, Max 3 tasks.
  Two target-tracking policies (scale-out if either triggers; scale-in when both allow):
  | Policy | Metric | Target | Scale Out Cooldown | Scale In Cooldown |
  |--------|--------|--------|-------------------|-------------------|
  | cpu-target-tracking | ECSServiceAverageCPUUtilization | 70% | 300s | 600s |
  | memory-target-tracking | ECSServiceAverageMemoryUtilization | 80% | 300s | 600s |

  SNS TOPIC:
  | Topic | ARN | Purpose |
  |-------|-----|---------|
  | ecs-deployment-alerts | arn:aws:sns:il-central-1:250598594267:ecs-deployment-alerts | ECS deployment/health alerts |
  Subscriptions: doradsoft@gmail.com (email)

  CLOUDWATCH ALARMS:
  Auto-created by Target Tracking:
  - CPU: AlarmHigh (scale-out when CPU > 70%), AlarmLow (scale-in when CPU < 70%)
  - Memory: AlarmHigh (scale-out when memory > 80%), AlarmLow (scale-in when memory < 80%)
  Custom deployment/health alarms:
  | Alarm | Metric | Condition | Period | Eval Periods | Action |
  |-------|--------|-----------|--------|-------------|--------|
  | ecs-website-deployment-failures | TaskSetFailedTaskCount | > 3 | 10 min | 1 | SNS: ecs-deployment-alerts |
  | ecs-website-no-running-tasks | RunningTaskCount | < 1 | 1 min | 3 | SNS: ecs-deployment-alerts |

Resources:
  # =============================================================================
  # ECS Website Log Group
  # =============================================================================
  ECSWebsiteLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/bible-on-site-website
      RetentionInDays: 180
      LogGroupClass: STANDARD
      Tags:
        - Key: Project
          Value: bible-on-site
        - Key: Service
          Value: website

  # =============================================================================
  # ECS API Log Group (for future use)
  # =============================================================================
  # ECSAPILogGroup:
  #   Type: AWS::Logs::LogGroup
  #   Properties:
  #     LogGroupName: /ecs/bible-on-site-api
  #     RetentionInDays: 180
  #     LogGroupClass: STANDARD
  #     Tags:
  #       - Key: Project
  #         Value: bible-on-site
  #       - Key: Service
  #         Value: api

  # =============================================================================
  # Application Auto Scaling - Scalable Target
  # =============================================================================
  WebsiteScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      ServiceNamespace: ecs
      ResourceId: service/bible-on-site-cluster/bible-on-site-website
      ScalableDimension: ecs:service:DesiredCount
      MinCapacity: 1
      MaxCapacity: 3
      # RoleARN is auto-created as AWSServiceRoleForApplicationAutoScaling_ECSService

  # =============================================================================
  # Application Auto Scaling - CPU Target Tracking Policy
  # =============================================================================
  WebsiteCPUScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: cpu-target-tracking
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref WebsiteScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 70.0
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization
        ScaleOutCooldown: 300
        ScaleInCooldown: 600

  # =============================================================================
  # Application Auto Scaling - Memory Target Tracking Policy
  # =============================================================================
  WebsiteMemoryScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: memory-target-tracking
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref WebsiteScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 80.0
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageMemoryUtilization
        ScaleOutCooldown: 300
        ScaleInCooldown: 600

  # =============================================================================
  # SNS Topic: ECS Deployment Alerts
  # =============================================================================
  ECSDeploymentAlertsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: ecs-deployment-alerts
      Tags:
        - Key: Project
          Value: bible-on-site

  ECSDeploymentAlertsEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref ECSDeploymentAlertsTopic
      Protocol: email
      Endpoint: doradsoft@gmail.com

  # =============================================================================
  # CloudWatch Alarm: Deployment Failures (stuck deployment detection)
  # =============================================================================
  # Triggers when > 3 tasks fail within a 10-minute window, indicating a
  # stuck or broken deployment (e.g. health check misconfiguration).
  WebsiteDeploymentFailuresAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: ecs-website-deployment-failures
      AlarmDescription: Alert when website ECS tasks fail repeatedly (stuck deployment)
      Namespace: ECS/ContainerInsights
      MetricName: TaskSetFailedTaskCount
      Dimensions:
        - Name: ClusterName
          Value: bible-on-site-cluster
        - Name: ServiceName
          Value: bible-on-site-website
      Statistic: Sum
      Period: 600
      EvaluationPeriods: 1
      Threshold: 3
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref ECSDeploymentAlertsTopic
      OKActions:
        - !Ref ECSDeploymentAlertsTopic
      Tags:
        - Key: Project
          Value: bible-on-site

  # =============================================================================
  # CloudWatch Alarm: No Running Tasks (website down detection)
  # =============================================================================
  # Triggers when RunningTaskCount < 1 for 3 consecutive 1-minute periods,
  # meaning the website has no healthy task and is down.
  WebsiteNoRunningTasksAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: ecs-website-no-running-tasks
      AlarmDescription: Alert when website has no running tasks (website down)
      Namespace: ECS/ContainerInsights
      MetricName: RunningTaskCount
      Dimensions:
        - Name: ClusterName
          Value: bible-on-site-cluster
        - Name: ServiceName
          Value: bible-on-site-website
      Statistic: Minimum
      Period: 60
      EvaluationPeriods: 3
      Threshold: 1
      ComparisonOperator: LessThanThreshold
      TreatMissingData: breaching
      AlarmActions:
        - !Ref ECSDeploymentAlertsTopic
      OKActions:
        - !Ref ECSDeploymentAlertsTopic
      Tags:
        - Key: Project
          Value: bible-on-site


Outputs:
  ECSDeploymentAlertsTopicArn:
    Description: SNS topic ARN for ECS deployment alerts
    Value: !Ref ECSDeploymentAlertsTopic
    Export:
      Name: !Sub "${AWS::StackName}-ECSDeploymentAlertsTopicArn"

  WebsiteLogGroupName:
    Description: Log group name for ECS Website service
    Value: !Ref ECSWebsiteLogGroup
    Export:
      Name: !Sub "${AWS::StackName}-WebsiteLogGroupName"

  WebsiteLogGroupArn:
    Description: Log group ARN for ECS Website service
    Value: !GetAtt ECSWebsiteLogGroup.Arn
    Export:
      Name: !Sub "${AWS::StackName}-WebsiteLogGroupArn"
