# ============================================================================
# ⚠️ DISCLAIMER: This CloudFormation template has NEVER been tested or deployed.
# It is maintained as Infrastructure as Code DOCUMENTATION ONLY to reflect the
# de-facto AWS configuration. Do not assume it will work without thorough testing.
# ============================================================================

AWSTemplateFormatVersion: "2010-09-09"
Description: |
  CloudWatch Log Groups and Auto Scaling for Bible On Site project.

  ⚠️ WARNING: This template is DOCUMENTATION ONLY and has never been deployed.

  This template documents the CloudWatch Logs configuration for ECS container logs
  and Application Auto Scaling configuration for ECS services.

  LOG GROUPS:
  | Log Group Name | Retention | Purpose |
  |----------------|-----------|---------|
  | /ecs/bible-on-site-website | 180 days | ECS Website container logs |

  Log streams are created automatically by ECS with the pattern:
  ecs/<container-name>/<task-id>

  AUTO SCALING (bible-on-site-website): Min 1, Max 3 tasks.
  Two target-tracking policies (scale-out if either triggers; scale-in when both allow):
  | Policy | Metric | Target | Scale Out Cooldown | Scale In Cooldown |
  |--------|--------|--------|-------------------|-------------------|
  | cpu-target-tracking | ECSServiceAverageCPUUtilization | 70% | 300s | 600s |
  | memory-target-tracking | ECSServiceAverageMemoryUtilization | 80% | 300s | 600s |

  CLOUDWATCH ALARMS (auto-created by Target Tracking):
  - CPU: AlarmHigh (scale-out when CPU > 70%), AlarmLow (scale-in when CPU < 70%)
  - Memory: AlarmHigh (scale-out when memory > 80%), AlarmLow (scale-in when memory < 80%)

Resources:
  # =============================================================================
  # ECS Website Log Group
  # =============================================================================
  ECSWebsiteLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/bible-on-site-website
      RetentionInDays: 180
      LogGroupClass: STANDARD
      Tags:
        - Key: Project
          Value: bible-on-site
        - Key: Service
          Value: website

  # =============================================================================
  # ECS API Log Group (for future use)
  # =============================================================================
  # ECSAPILogGroup:
  #   Type: AWS::Logs::LogGroup
  #   Properties:
  #     LogGroupName: /ecs/bible-on-site-api
  #     RetentionInDays: 180
  #     LogGroupClass: STANDARD
  #     Tags:
  #       - Key: Project
  #         Value: bible-on-site
  #       - Key: Service
  #         Value: api

  # =============================================================================
  # Application Auto Scaling - Scalable Target
  # =============================================================================
  WebsiteScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      ServiceNamespace: ecs
      ResourceId: service/bible-on-site-cluster/bible-on-site-website
      ScalableDimension: ecs:service:DesiredCount
      MinCapacity: 1
      MaxCapacity: 3
      # RoleARN is auto-created as AWSServiceRoleForApplicationAutoScaling_ECSService

  # =============================================================================
  # Application Auto Scaling - CPU Target Tracking Policy
  # =============================================================================
  WebsiteCPUScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: cpu-target-tracking
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref WebsiteScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 70.0
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization
        ScaleOutCooldown: 300
        ScaleInCooldown: 600

  # =============================================================================
  # Application Auto Scaling - Memory Target Tracking Policy
  # =============================================================================
  WebsiteMemoryScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: memory-target-tracking
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref WebsiteScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 80.0
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageMemoryUtilization
        ScaleOutCooldown: 300
        ScaleInCooldown: 600

Outputs:
  WebsiteLogGroupName:
    Description: Log group name for ECS Website service
    Value: !Ref ECSWebsiteLogGroup
    Export:
      Name: !Sub "${AWS::StackName}-WebsiteLogGroupName"

  WebsiteLogGroupArn:
    Description: Log group ARN for ECS Website service
    Value: !GetAtt ECSWebsiteLogGroup.Arn
    Export:
      Name: !Sub "${AWS::StackName}-WebsiteLogGroupArn"
