# ============================================================================
# ⚠️ DISCLAIMER: This CloudFormation template has NEVER been tested or deployed.
# It is maintained as Infrastructure as Code DOCUMENTATION ONLY to reflect the
# de-facto AWS configuration. Do not assume it will work without thorough testing.
# ============================================================================

AWSTemplateFormatVersion: "2010-09-09"
Description: |
  Route53 Hosted Zones and DNS Records for Bible On Site project.

  ⚠️ WARNING: This template is DOCUMENTATION ONLY and has never been deployed.

  This template documents the Route53 configuration for the project domains:
  - תנך.com (xn--febl3a.com) - Punycode encoded Hebrew domain
  - תנך.co.il (xn--febl3a.co.il) - Punycode encoded Hebrew domain

  Both domains point to the EC2 Nginx reverse proxy.

  Note: The bible-on-site.local private hosted zone is managed by Cloud Map
  and is NOT included in this template.

  Sensitive Information Restoration:
  | Placeholder | Description | Restoration Command |
  |---|---|---|
  | `<EC2_PUBLIC_IP>` | EC2 Nginx public IP | `aws ec2 describe-instances --filters "Name=tag:Name,Values=nginx" --query "Reservations[0].Instances[0].PublicIpAddress" --output text` |
  | `<HOSTED_ZONE_ID_COM>` | Hosted zone ID for xn--febl3a.com | `aws route53 list-hosted-zones-by-name --dns-name xn--febl3a.com --query "HostedZones[0].Id" --output text` |
  | `<HOSTED_ZONE_ID_COIL>` | Hosted zone ID for xn--febl3a.co.il | `aws route53 list-hosted-zones-by-name --dns-name xn--febl3a.co.il --query "HostedZones[0].Id" --output text` |
  | `<HOSTED_ZONE_ID_LOCAL>` | Private hosted zone for Cloud Map | `aws route53 list-hosted-zones-by-name --dns-name bible-on-site.local --query "HostedZones[0].Id" --output text` |

  HOSTED ZONES:
  | Domain | Hosted Zone ID | Type |
  |--------|----------------|------|
  | xn--febl3a.com (תנך.com) | `<HOSTED_ZONE_ID_COM>` | Public |
  | xn--febl3a.co.il (תנך.co.il) | `<HOSTED_ZONE_ID_COIL>` | Public |
  | bible-on-site.local | `<HOSTED_ZONE_ID_LOCAL>` | Private (Cloud Map) |

Parameters:
  EC2PublicIP:
    Type: String
    # Default: <EC2_PUBLIC_IP> - See Sensitive Information Restoration table above
    Description: Public IP address of the EC2 Nginx instance

Resources:
  # =============================================================================
  # Hosted Zone: תנך.com (xn--febl3a.com)
  # =============================================================================
  HostedZoneTanachCom:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: xn--febl3a.com
      HostedZoneConfig:
        Comment: "Hebrew domain תנך.com"
      HostedZoneTags:
        - Key: Project
          Value: bible-on-site
        - Key: Domain
          Value: tanach.com

  # A Record: xn--febl3a.com -> EC2 Nginx
  ARecordTanachCom:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneTanachCom
      Name: xn--febl3a.com
      Type: A
      TTL: 300
      ResourceRecords:
        - !Ref EC2PublicIP

  # CNAME: www.xn--febl3a.com -> xn--febl3a.com
  WwwCnameTanachCom:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneTanachCom
      Name: www.xn--febl3a.com
      Type: CNAME
      TTL: 300
      ResourceRecords:
        - xn--febl3a.com

  # Wildcard CNAME: *.xn--febl3a.com -> xn--febl3a.com
  WildcardCnameTanachCom:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneTanachCom
      Name: "*.xn--febl3a.com"
      Type: CNAME
      TTL: 300
      ResourceRecords:
        - xn--febl3a.com

  # =============================================================================
  # Hosted Zone: תנך.co.il (xn--febl3a.co.il)
  # =============================================================================
  HostedZoneTanachCoIl:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: xn--febl3a.co.il
      HostedZoneConfig:
        Comment: "Hebrew domain תנך.co.il"
      HostedZoneTags:
        - Key: Project
          Value: bible-on-site
        - Key: Domain
          Value: tanach.co.il

  # A Record: xn--febl3a.co.il -> EC2 Nginx
  ARecordTanachCoIl:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneTanachCoIl
      Name: xn--febl3a.co.il
      Type: A
      TTL: 300
      ResourceRecords:
        - !Ref EC2PublicIP

  # CNAME: www.xn--febl3a.co.il -> xn--febl3a.co.il
  WwwCnameTanachCoIl:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneTanachCoIl
      Name: www.xn--febl3a.co.il
      Type: CNAME
      TTL: 300
      ResourceRecords:
        - xn--febl3a.co.il

  # Wildcard CNAME: *.xn--febl3a.co.il -> xn--febl3a.co.il
  WildcardCnameTanachCoIl:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneTanachCoIl
      Name: "*.xn--febl3a.co.il"
      Type: CNAME
      TTL: 300
      ResourceRecords:
        - xn--febl3a.co.il

Outputs:
  HostedZoneTanachComId:
    Description: Hosted Zone ID for תנך.com
    Value: !Ref HostedZoneTanachCom
    Export:
      Name: !Sub "${AWS::StackName}-HostedZoneTanachComId"

  HostedZoneTanachCoIlId:
    Description: Hosted Zone ID for תנך.co.il
    Value: !Ref HostedZoneTanachCoIl
    Export:
      Name: !Sub "${AWS::StackName}-HostedZoneTanachCoIlId"

  NameServersTanachCom:
    Description: Name servers for תנך.com (configure at domain registrar)
    Value: !Join [", ", !GetAtt HostedZoneTanachCom.NameServers]

  NameServersTanachCoIl:
    Description: Name servers for תנך.co.il (configure at domain registrar)
    Value: !Join [", ", !GetAtt HostedZoneTanachCoIl.NameServers]
