// Data Deployer - Populates production database with SQL structure and data via Lambda
//
// Deploys:
// - Static structure (sefarim, perakim, dates)
// - Perushim structure and data (parshanim, perushim, notes — generated by Sefaria pipeline)
// - Tanahpedia structure + baseline lookups + seed content
//
// The populator Lambda injects `DROP TABLE IF EXISTS` before every `CREATE TABLE`
// (see docs/aws/cloudformation/data-deploy/data-deploy-lambda.py), so every deploy
// rebuilds the structure and re-seeds — the same files can be re-run on each release
// dispatch without "already exists" or duplicate-row errors.
//
// Dynamic structure (articles, dedications, authors, etc.) is managed manually via admin zone.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { InvokeCommand, LambdaClient } from "@aws-sdk/client-lambda";
import {
	DeleteObjectsCommand,
	PutObjectCommand,
	S3Client,
} from "@aws-sdk/client-s3";
import * as dotenv from "dotenv";
import { DeployerBase } from "../deployer-base.mjs";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Load environment variables
dotenv.config({
	path: "./deploy/data-deploy/.env",
});

// Configuration
const S3_BUCKET = "bible-on-site-data-deploy";
const LAMBDA_FUNCTION_NAME = "bible-on-site-db-populator";

// SQL files to deploy (order matters: structure before data)
const SQL_FILES = [
	"tanah_static_structure.sql",
	"tanah_sefarim_and_perakim_data.sql",
	"perushim_structure.sql",
	"perushim_data.sql",
	// Tanahpedia (order: structure -> baseline lookups -> seed content).
	// The populator Lambda drop+recreates each table it sees a CREATE TABLE for,
	// so these rebuild the Tanahpedia schema and re-seed the curated entries on
	// every deploy — no accumulation, no duplicate-key errors. The upgrade-only
	// alter script (tanahpedia_alter_source_citation.sql) is intentionally omitted:
	// tanahpedia_structure.sql already defines the final schema, so the alter would
	// fail with a duplicate-column error against the freshly created tables.
	"tanahpedia_structure.sql",
	"tanahpedia_seed_data.sql",
	"tanahpedia_incremental_lookups.sql",
	"tanahpedia_legacy_migration.sql",
];

class DataDeployer extends DeployerBase {
	private readonly region: string;
	private readonly dataDir: string;
	private readonly sqlFiles = SQL_FILES;
	private s3Prefix = "";

	constructor() {
		super("data");

		const region = process.env.AWS_REGION;

		if (!region) {
			throw new Error("AWS_REGION environment variable is required");
		}

		this.region = region;
		this.dataDir = path.resolve(__dirname, "../../../data/mysql");
	}

	protected override async deployPreConditions(): Promise<void> {
		this.info("Checking preconditions...");

		// Verify all SQL files exist
		for (const sqlFile of this.sqlFiles) {
			const filePath = path.join(this.dataDir, sqlFile);
			if (!fs.existsSync(filePath)) {
				throw new Error(`Required SQL file not found: ${filePath}`);
			}
		}

		this.info("Preconditions passed.");
	}

	protected override async coreDeploy(): Promise<void> {
		const s3Client = new S3Client({ region: this.region });
		const lambdaClient = new LambdaClient({ region: this.region });

		try {
			// Upload SQL files to S3
			await this.uploadSqlFiles(s3Client);

			// Invoke Lambda to populate database
			await this.invokeLambda(lambdaClient);
		} finally {
			// Cleanup S3 files
			await this.cleanupS3Files(s3Client);
		}
	}

	private async uploadSqlFiles(s3Client: S3Client): Promise<void> {
		const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
		this.s3Prefix = `sql/${timestamp}/`;

		this.info(`Uploading SQL files to s3://${S3_BUCKET}/${this.s3Prefix}...`);

		for (const sqlFile of this.sqlFiles) {
			const filePath = path.join(this.dataDir, sqlFile);
			const content = fs.readFileSync(filePath);

			await s3Client.send(
				new PutObjectCommand({
					Bucket: S3_BUCKET,
					Key: `${this.s3Prefix}${sqlFile}`,
					Body: content,
					ContentType: "text/plain",
				}),
			);

			this.info(`Uploaded: ${sqlFile}`);
		}
	}

	private async invokeLambda(lambdaClient: LambdaClient): Promise<void> {
		this.info(`Invoking Lambda function: ${LAMBDA_FUNCTION_NAME}...`);

		const payload = {
			sql_files: this.sqlFiles,
			s3_prefix: this.s3Prefix,
		};

		const response = await lambdaClient
			.send(
				new InvokeCommand({
					FunctionName: LAMBDA_FUNCTION_NAME,
					Payload: Buffer.from(JSON.stringify(payload)),
					LogType: "Tail",
				}),
			)
			.catch((err: unknown) => {
				const status = (
					err as { $metadata?: { httpStatusCode?: number } }
				)?.$metadata?.httpStatusCode;
				const reason = err instanceof Error ? err.message : String(err);
				// A 5xx is a service-side fault thrown before any response/tail-log
				// is available: the Lambda runtime itself failed to run (bad
				// package, init crash, deprecated runtime, OOM). Its code is
				// maintained outside this repo, so point at CloudWatch. Other
				// errors (4xx: AccessDenied, ResourceNotFound, invalid params) are
				// caller/config issues where the function never ran.
				const isServerFault = status !== undefined && status >= 500;
				const guidance = isServerFault
					? ` This is a Lambda runtime/service fault, not a data error. ` +
						`Inspect the function's CloudWatch Logs ` +
						`(/aws/lambda/${LAMBDA_FUNCTION_NAME}) and verify it is deployed ` +
						`with a supported runtime.`
					: ` The invocation request itself failed (likely a permissions, ` +
						`configuration, or missing-function issue); the function may ` +
						`never have run.`;
				throw new Error(
					`Failed to invoke Lambda '${LAMBDA_FUNCTION_NAME}'` +
						(status ? ` (HTTP ${status})` : "") +
						`: ${reason}.${guidance}`,
					{ cause: err },
				);
			});

		// Decode and log the Lambda logs
		if (response.LogResult) {
			const logs = Buffer.from(response.LogResult, "base64").toString("utf-8");
			this.info("Lambda logs:");
			console.log(logs);
		}

		// Check for errors
		if (response.FunctionError) {
			const errorPayload = response.Payload
				? JSON.parse(Buffer.from(response.Payload).toString("utf-8"))
				: {};
			throw new Error(
				`Lambda execution failed: ${errorPayload.errorMessage || response.FunctionError}`,
			);
		}

		// Parse response
		const result = response.Payload
			? JSON.parse(Buffer.from(response.Payload).toString("utf-8"))
			: {};

		this.info("Lambda response:");
		console.log(JSON.stringify(result, null, 2));

		if (result.statusCode !== 200) {
			throw new Error(
				`Lambda returned non-200 status: ${JSON.stringify(result)}`,
			);
		}

		this.info("Database population completed successfully.");
	}

	private async cleanupS3Files(s3Client: S3Client): Promise<void> {
		if (!this.s3Prefix) return;

		this.info(`Cleaning up S3 files at s3://${S3_BUCKET}/${this.s3Prefix}...`);

		try {
			await s3Client.send(
				new DeleteObjectsCommand({
					Bucket: S3_BUCKET,
					Delete: {
						Objects: this.sqlFiles.map((f) => ({
							Key: `${this.s3Prefix}${f}`,
						})),
					},
				}),
			);
			this.info("S3 cleanup completed.");
		} catch (error) {
			this.warn(`S3 cleanup failed (non-fatal): ${error}`);
		}
	}
}

// Main entry point
const deployer = new DataDeployer();
await deployer.deploy();
