import { createHash } from "node:crypto";
import { existsSync, readdirSync, readFileSync, statSync } from "node:fs";
import { join, resolve } from "node:path";
import { expect, test } from "@playwright/test";
import { reportBenchmark } from "../util/benchmark";

const NEXT_BUILD_DIR = resolve(__dirname, "../../.next");
const STANDALONE_DIR = resolve(NEXT_BUILD_DIR, "standalone");

/**
 * Get directory size in bytes using Node.js fs APIs.
 * Recursively calculates the total size of all files in the directory.
 */
function getDirectorySizeBytes(dirPath: string): number {
	if (!existsSync(dirPath)) {
		throw new Error(`Directory does not exist: ${dirPath}`);
	}

	let totalSize = 0;

	function calculateSize(currentPath: string): void {
		const stats = statSync(currentPath);

		if (stats.isFile()) {
			totalSize += stats.size;
		} else if (stats.isDirectory()) {
			const entries = readdirSync(currentPath);
			for (const entry of entries) {
				calculateSize(join(currentPath, entry));
			}
		}
	}

	calculateSize(dirPath);
	return totalSize;
}

const BYTES_PER_MB = 1024 * 1024;

test.describe("Build Size Benchmarks", () => {
	// Only run once (skip on non-Desktop projects since we don't need a browser)
	// biome-ignore lint/correctness/noEmptyPattern: Playwright requires object destructuring for fixtures
	test.beforeEach(({}, testInfo) => {
		if (testInfo.project.name !== "Desktop") {
			testInfo.skip(true, "Build size tests only run once, not per browser");
		}
	});

	test("browser scripts stay below 5 MB each", () => {
		const chunks = resolve(NEXT_BUILD_DIR, "static/chunks");
		const scripts = readdirSync(chunks, { recursive: true }).filter(
			(file) => typeof file === "string" && file.endsWith(".js"),
		);
		expect(scripts.length).toBeGreaterThan(0);
		for (const script of scripts) {
			const bytes = statSync(join(chunks, script as string)).size;
			expect(
				bytes,
				`${script} must not include the complete canonical corpus`,
			).toBeLessThan(5 * BYTES_PER_MB);
		}
	});

	test("standalone reader assets preserve their content hashes and generated bytes", () => {
		const website = resolve(__dirname, "../..");
		const catalog = JSON.parse(
			readFileSync(
				resolve(website, "src/data/db/client-catalog.generated.json"),
				"utf8",
			),
		) as { books: { file: string }[] };
		expect(catalog.books).toHaveLength(35);
		for (const { file } of catalog.books) {
			const source = readFileSync(join(website, "public", file.slice(1)));
			const deployed = readFileSync(
				join(STANDALONE_DIR, "public", file.slice(1)),
			);
			expect(
				deployed.equals(source),
				`${file} must preserve all canonical bytes`,
			).toBe(true);
			const digest = file.split(".").at(-2);
			expect(createHash("sha256").update(deployed).digest("hex")).toBe(digest);
		}
	});

	test.describe("Standalone bundle size", () => {
		test("Remains below 12000MB", () => {
			expect(
				existsSync(STANDALONE_DIR),
				`Standalone directory should exist at ${STANDALONE_DIR}. Run 'npm run build' first.`,
			).toBe(true);

			const sizeBytes = getDirectorySizeBytes(STANDALONE_DIR);
			const sizeMB = sizeBytes / BYTES_PER_MB;

			console.log(
				`Standalone bundle size: ${sizeMB.toFixed(2)} MB (${sizeBytes} bytes)`,
			);

			const MAX_SIZE_MB = 12000;
			reportBenchmark({
				name: "build: standalone",
				measure: "size_mb",
				value: sizeMB,
				upperValue: MAX_SIZE_MB,
			});

			expect(sizeMB).toBeLessThan(MAX_SIZE_MB);
		});
	});

	test.describe(".next directory size", () => {
		test("Remains below 24000MB", () => {
			expect(
				existsSync(NEXT_BUILD_DIR),
				`Build directory should exist at ${NEXT_BUILD_DIR}. Run 'npm run build' first.`,
			).toBe(true);

			const sizeBytes = getDirectorySizeBytes(NEXT_BUILD_DIR);
			const sizeMB = sizeBytes / BYTES_PER_MB;

			console.log(
				`Total .next directory size: ${sizeMB.toFixed(2)} MB (${sizeBytes} bytes)`,
			);

			const MAX_SIZE_MB = 24000;
			reportBenchmark({
				name: "build: .next",
				measure: "size_mb",
				value: sizeMB,
				upperValue: MAX_SIZE_MB,
			});

			expect(sizeMB).toBeLessThan(MAX_SIZE_MB);
		});
	});
});
