import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import { expect, test } from "@playwright/test";
import { reportBenchmark } from "../util/benchmark";

const NEXT_BUILD_DIR = resolve(__dirname, "../../.next");
const PRERENDER_MANIFEST_PATH = resolve(
	NEXT_BUILD_DIR,
	"prerender-manifest.json",
);

interface PrerenderManifestRoute {
	initialRevalidateSeconds: number | false;
	srcRoute: string | null;
	dataRoute: string | null;
}

interface PrerenderManifestDynamicRoute {
	routeRegex: string;
	dataRoute: string | null;
	fallback: string | null | false;
}

interface PrerenderManifest {
	version: number;
	routes: Record<string, PrerenderManifestRoute>;
	dynamicRoutes: Record<string, PrerenderManifestDynamicRoute>;
	notFoundRoutes: string[];
	preview: unknown;
}

function loadPrerenderManifest(): PrerenderManifest {
	expect(
		existsSync(PRERENDER_MANIFEST_PATH),
		`prerender-manifest.json should exist at ${PRERENDER_MANIFEST_PATH}. Run 'npm run build' first.`,
	).toBe(true);

	return JSON.parse(readFileSync(PRERENDER_MANIFEST_PATH, "utf8"));
}

/**
 * Routes that MUST be statically prerendered (SSG) at build time.
 * A representative sample — not exhaustive, but enough to catch regressions
 * like an accidental `headers()` call that forces everything dynamic.
 */
function getExpectedSSGRoutes(): string[] {
	const ssgRoutes: string[] = [];

	// Static section pages (generated by [section]/page.tsx generateStaticParams)
	const sections = [
		"dailyBulletin",
		"whatsappGroup",
		"tos",
		"app",
		"contact",
		"donation",
		"tanah-sefarim",
	];
	for (const section of sections) {
		ssgRoutes.push(`/${section}`);
	}

	// Static standalone pages
	ssgRoutes.push("/");
	ssgRoutes.push("/bookshelf");
	ssgRoutes.push("/journalism");
	ssgRoutes.push("/rabbis-blessing");
	ssgRoutes.push("/929/authors");

	// Sample of perek pages (first, middle, last)
	const samplePerakim = [1, 2, 100, 465, 500, 700, 928, 929];
	for (const perek of samplePerakim) {
		ssgRoutes.push(`/929/${perek}`);
	}

	return ssgRoutes;
}

/**
 * Dynamic route patterns that MUST exist in the prerender manifest.
 * These are routes with `generateStaticParams` that have dynamic segments.
 */
const EXPECTED_DYNAMIC_ROUTE_PATTERNS = [
	"/[section]",
	"/929/[number]",
	"/929/[number]/[slug]",
	"/929/authors/[authorParam]",
];

/**
 * Routes that must NOT appear in the prerender manifest (dynamic/SSR only).
 * - /929 redirects to today's perek (runtime-dependent)
 * - /dev/sefer/[number] is force-dynamic
 */
const EXPECTED_NON_SSG_ROUTES = ["/929"];

test.describe("Route Rendering Modes", () => {
	// biome-ignore lint/correctness/noEmptyPattern: Playwright requires object destructuring for fixtures
	test.beforeEach(({}, testInfo) => {
		if (testInfo.project.name !== "Desktop") {
			testInfo.skip(true, "Route rendering tests only run once");
		}
	});

	let manifest: PrerenderManifest;

	test.beforeAll(() => {
		manifest = loadPrerenderManifest();
	});

	test.describe("SSG routes are prerendered", () => {
		test("all expected static routes exist in prerender manifest", () => {
			const expectedSSG = getExpectedSSGRoutes();
			const missingRoutes: string[] = [];

			for (const route of expectedSSG) {
				if (!(route in manifest.routes)) {
					missingRoutes.push(route);
				}
			}

			expect(
				missingRoutes,
				`These routes should be statically prerendered but are missing from the manifest. ` +
					`This usually means a component in the render tree calls a dynamic API ` +
					`(headers(), cookies(), searchParams) which forces the route to be server-rendered. ` +
					`Missing routes: ${missingRoutes.join(", ")}`,
			).toEqual([]);

			reportBenchmark({
				name: "routes: SSG verified",
				measure: "count",
				value: expectedSSG.length,
			});
		});

		test("all 929 perakim (1-929) are prerendered", () => {
			let prerenderedCount = 0;
			const missingPerakim: number[] = [];

			for (let i = 1; i <= 929; i++) {
				if (`/929/${i}` in manifest.routes) {
					prerenderedCount++;
				} else {
					missingPerakim.push(i);
				}
			}

			expect(
				missingPerakim.length,
				`${missingPerakim.length} perakim missing from SSG. First 10: ${missingPerakim.slice(0, 10).join(", ")}`,
			).toBe(0);

			reportBenchmark({
				name: "routes: SSG perakim",
				measure: "count",
				value: prerenderedCount,
				upperValue: 929,
			});
		});

		test("commentary pages (slug routes) are prerendered at build (SSG)", () => {
			const commentaryRoutes = Object.keys(manifest.routes).filter(
				(route) => /^\/929\/\d+\/[^/]+$/.test(route),
			);

			expect(
				commentaryRoutes.length,
				"Commentary pages (/929/[number]/[slug]) should be fully SSG. " +
					"If zero routes appear here, generateStaticParams may have been reverted to return [].",
			).toBeGreaterThan(0);

			reportBenchmark({
				name: "routes: SSG commentary",
				measure: "count",
				value: commentaryRoutes.length,
			});
		});
	});

	test.describe("Dynamic route patterns exist", () => {
		test("expected dynamic route patterns are registered", () => {
			const missingPatterns: string[] = [];

			for (const pattern of EXPECTED_DYNAMIC_ROUTE_PATTERNS) {
				if (!(pattern in manifest.dynamicRoutes)) {
					missingPatterns.push(pattern);
				}
			}

			expect(
				missingPatterns,
				`These dynamic route patterns should exist in the manifest: ${missingPatterns.join(", ")}`,
			).toEqual([]);
		});
	});

	test.describe("Non-SSG routes are NOT prerendered", () => {
		test("dynamic/SSR-only routes are absent from static manifest", () => {
			const wronglyStatic: string[] = [];

			for (const route of EXPECTED_NON_SSG_ROUTES) {
				if (route in manifest.routes) {
					wronglyStatic.push(route);
				}
			}

			expect(
				wronglyStatic,
				`These routes should NOT be statically prerendered but were found in the manifest: ${wronglyStatic.join(", ")}`,
			).toEqual([]);
		});
	});

	test.describe("Total prerendered route count", () => {
		test("reports total SSG routes for tracking", () => {
			const totalRoutes = Object.keys(manifest.routes).length;
			const totalDynamic = Object.keys(manifest.dynamicRoutes).length;

			console.log(`Total prerendered routes: ${totalRoutes}`);
			console.log(`Total dynamic route patterns: ${totalDynamic}`);

			reportBenchmark({
				name: "routes: total SSG",
				measure: "count",
				value: totalRoutes,
			});

			reportBenchmark({
				name: "routes: total dynamic patterns",
				measure: "count",
				value: totalDynamic,
			});

			// Sanity: 929 perakim + 7 sections + commentary pages + a few more
			expect(totalRoutes).toBeGreaterThan(2000);
		});
	});
});
