//! Generate MySQL SQL file from pipeline output.
//!
//! Generates INSERT statements for all three entities:
//! - `parshan` and `perush` tables (for joins/reference)
//! - `note` table (the large commentary text data, primary web delivery)

use anyhow::Result;
use std::fs;
use std::path::Path;

use crate::data::extract::{Extracted, Note, Parshan, Perush};

pub fn generate(
    extracted: &Extracted,
    dump_name: &str,
    output_to_dependant_modules: bool,
) -> Result<()> {
    let output_path = if output_to_dependant_modules {
        Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../../mysql")
            .join("perushim_data.sql")
    } else {
        let outputs_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join(".output");
        fs::create_dir_all(&outputs_dir)?;
        outputs_dir.join(format!("{}.perushim_data.sql", dump_name))
    };

    generate_sql(&output_path, extracted, dump_name)?;
    println!("📁 Written to: {}", output_path.display());

    Ok(())
}

fn generate_sql(path: &Path, extracted: &Extracted, dump_name: &str) -> Result<()> {
    let mut sql = String::new();

    sql.push_str("-- Generated by: cd data && cargo make generate-perushim-view-mysql\n");
    sql.push_str(&format!("-- Source: {}\n", dump_name));
    sql.push_str(&format!(
        "-- Generated at: {}\n",
        chrono::Utc::now().format("%Y-%m-%d %H:%M:%S UTC")
    ));
    sql.push_str(
        "-- Database selection handled by the executing tool (db-populator, Lambda, etc.)\n\n",
    );

    sql.push_str("SET NAMES utf8mb4;\n");
    sql.push_str("SET FOREIGN_KEY_CHECKS = 0;\n\n");

    // Truncate perushim tables before loading full dataset — test data
    // (tanah_test_data.sql) may have already inserted rows with the same PKs.
    sql.push_str("TRUNCATE TABLE note;\n");
    sql.push_str("TRUNCATE TABLE perush;\n");
    sql.push_str("TRUNCATE TABLE parshan;\n\n");

    generate_parshanim_sql(&mut sql, &extracted.parshanim);
    generate_perushim_sql(&mut sql, &extracted.perushim);
    generate_notes_sql(&mut sql, &extracted.notes);

    sql.push_str("\nSET FOREIGN_KEY_CHECKS = 1;\n");

    fs::write(path, sql)?;

    Ok(())
}

fn escape_sql(s: &str) -> String {
    // Use SQL-standard doubled-quote escaping ('') instead of backslash (\')
    // to avoid issues with NO_BACKSLASH_ESCAPES mode and Lambda SQL parsers.
    s.replace('\\', "\\\\")
        .replace('\'', "''")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t")
}

fn generate_parshanim_sql(sql: &mut String, parshanim: &[Parshan]) {
    sql.push_str("-- parshan\n");
    for p in parshanim {
        let birth = p
            .birth_year
            .map(|y| y.to_string())
            .unwrap_or_else(|| "NULL".to_string());
        sql.push_str(&format!(
            "INSERT INTO parshan (id, name, birth_year, has_pic) VALUES ({}, '{}', {}, {});\n",
            p.id,
            escape_sql(&p.name),
            birth,
            if p.has_pic { 1 } else { 0 }
        ));
    }
    sql.push('\n');
}

fn generate_perushim_sql(sql: &mut String, perushim: &[Perush]) {
    sql.push_str("-- perush\n");
    for p in perushim {
        let comp_date_str = p
            .comp_date
            .as_ref()
            .map(|s| format!("'{}'", escape_sql(s)))
            .unwrap_or_else(|| "NULL".to_string());
        let pub_date_str = p
            .pub_date
            .as_ref()
            .map(|s| format!("'{}'", escape_sql(s)))
            .unwrap_or_else(|| "NULL".to_string());

        sql.push_str(&format!(
            "INSERT INTO perush (id, name, parshan_id, comp_date, pub_date, priority) VALUES ({}, '{}', {}, {}, {}, {});\n",
            p.id,
            escape_sql(&p.name),
            p.parshan_id,
            comp_date_str,
            pub_date_str,
            p.priority
        ));
    }
    sql.push('\n');
}

/// Batch size for multi-row INSERT statements.
/// Keeps each statement well under MySQL's `max_allowed_packet` default (64 MB).
const NOTES_BATCH_SIZE: usize = 500;

fn generate_notes_sql(sql: &mut String, notes: &[Note]) {
    sql.push_str("-- note\n");
    for chunk in notes.chunks(NOTES_BATCH_SIZE) {
        sql.push_str(
            "INSERT INTO note (perush_id, perek_id, pasuk, note_idx, note_content) VALUES\n",
        );
        for (i, n) in chunk.iter().enumerate() {
            if i > 0 {
                sql.push_str(",\n");
            }
            sql.push_str(&format!(
                "({}, {}, {}, {}, '{}')",
                n.perush_id,
                n.perek_id,
                n.pasuk,
                n.note_idx,
                escape_sql(&n.note_content)
            ));
        }
        sql.push_str(";\n");
    }
    sql.push('\n');
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_extracted(note_count: usize) -> Extracted {
        Extracted {
            parshanim: vec![
                Parshan {
                    id: 1,
                    name: "Rashi's \\ path".to_string(),
                    birth_year: Some(1040),
                    has_pic: true,
                },
                Parshan {
                    id: 2,
                    name: "Unknown".to_string(),
                    birth_year: None,
                    has_pic: false,
                },
            ],
            perushim: vec![
                Perush {
                    id: 10,
                    name: "Commentary One".to_string(),
                    parshan_id: 1,
                    comp_date: Some("1100".to_string()),
                    pub_date: None,
                    priority: 20,
                },
                Perush {
                    id: 11,
                    name: "Commentary Two".to_string(),
                    parshan_id: 2,
                    comp_date: None,
                    pub_date: Some("1200".to_string()),
                    priority: 30,
                },
            ],
            notes: (0..note_count)
                .map(|idx| Note {
                    perush_id: 10,
                    perek_id: 1,
                    pasuk: (idx % 5) as i64 + 1,
                    note_idx: idx as i64,
                    note_content: format!("note '{idx}'\nline"),
                })
                .collect(),
        }
    }

    #[test]
    fn escape_sql_uses_standard_quotes_and_control_escapes() {
        assert_eq!(escape_sql("a\\b'c\nd\re\tf"), "a\\\\b''c\\nd\\re\\tf");
    }

    #[test]
    fn generate_parshanim_sql_handles_optional_birth_year_and_picture_flag() {
        let mut sql = String::new();

        generate_parshanim_sql(&mut sql, &sample_extracted(0).parshanim);

        assert!(sql.contains("-- parshan"));
        assert!(sql.contains("Rashi''s \\\\ path', 1040, 1"));
        assert!(sql.contains("'Unknown', NULL, 0"));
    }

    #[test]
    fn generate_perushim_sql_handles_optional_dates() {
        let mut sql = String::new();

        generate_perushim_sql(&mut sql, &sample_extracted(0).perushim);

        assert!(sql.contains("'Commentary One', 1, '1100', NULL, 20"));
        assert!(sql.contains("'Commentary Two', 2, NULL, '1200', 30"));
    }

    #[test]
    fn generate_notes_sql_batches_large_note_sets() {
        let mut sql = String::new();

        generate_notes_sql(&mut sql, &sample_extracted(NOTES_BATCH_SIZE + 1).notes);

        assert_eq!(sql.matches("INSERT INTO note").count(), 2);
        assert!(sql.contains("(10, 1, 1, 0, 'note ''0''\\nline')"));
        assert!(sql.contains("(10, 1, 1, 500, 'note ''500''\\nline')"));
    }

    #[test]
    fn generate_sql_writes_complete_perushim_seed_file() {
        let dir = std::env::temp_dir().join(format!("perushim_mysql_test_{}", std::process::id()));
        fs::create_dir_all(&dir).unwrap();
        let path = dir.join("perushim.sql");

        generate_sql(&path, &sample_extracted(2), "dump-name").unwrap();

        let sql = fs::read_to_string(&path).unwrap();
        assert!(sql.contains("-- Source: dump-name"));
        assert!(sql.contains("SET NAMES utf8mb4;"));
        assert!(sql.contains("SET FOREIGN_KEY_CHECKS = 0;"));
        assert!(sql.contains("TRUNCATE TABLE note;"));
        assert!(sql.contains("TRUNCATE TABLE perush;"));
        assert!(sql.contains("TRUNCATE TABLE parshan;"));
        assert!(sql.contains("INSERT INTO parshan"));
        assert!(sql.contains("INSERT INTO perush"));
        assert!(sql.contains("INSERT INTO note"));
        assert!(sql.contains("SET FOREIGN_KEY_CHECKS = 1;"));

        fs::remove_dir_all(&dir).ok();
    }
}
