//! Generate MySQL SQL file from pipeline output.
//!
//! Generates INSERT statements for all three entities:
//! - `parshan` and `perush` tables (for joins/reference)
//! - `note` table (the large commentary text data, primary web delivery)

use anyhow::Result;
use std::fs;
use std::path::Path;

use crate::data::extract::{Extracted, Note, Parshan, Perush};

pub fn generate(
    extracted: &Extracted,
    dump_name: &str,
    output_to_dependant_modules: bool,
) -> Result<()> {
    let output_path = if output_to_dependant_modules {
        Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../../mysql")
            .join("perushim_data.sql")
    } else {
        let outputs_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join(".output");
        fs::create_dir_all(&outputs_dir)?;
        outputs_dir.join(format!("{}.perushim_data.sql", dump_name))
    };

    generate_sql(&output_path, extracted, dump_name)?;
    println!("📁 Written to: {}", output_path.display());

    Ok(())
}

fn generate_sql(path: &Path, extracted: &Extracted, dump_name: &str) -> Result<()> {
    let mut sql = String::new();

    sql.push_str("-- Generated by: cd data && cargo make generate-perushim-view-mysql\n");
    sql.push_str(&format!("-- Source: {}\n", dump_name));
    sql.push_str(&format!(
        "-- Generated at: {}\n",
        chrono::Utc::now().format("%Y-%m-%d %H:%M:%S UTC")
    ));
    sql.push_str(
        "-- Database selection handled by the executing tool (db-populator, Lambda, etc.)\n\n",
    );

    sql.push_str("SET NAMES utf8mb4;\n");
    sql.push_str("SET FOREIGN_KEY_CHECKS = 0;\n\n");

    generate_parshanim_sql(&mut sql, &extracted.parshanim);
    generate_perushim_sql(&mut sql, &extracted.perushim);
    generate_notes_sql(&mut sql, &extracted.notes);

    sql.push_str("\nSET FOREIGN_KEY_CHECKS = 1;\n");

    fs::write(path, sql)?;

    Ok(())
}

fn escape_sql(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('\'', "\\'")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t")
}

fn generate_parshanim_sql(sql: &mut String, parshanim: &[Parshan]) {
    sql.push_str("-- parshan\n");
    for p in parshanim {
        let birth = p
            .birth_year
            .map(|y| y.to_string())
            .unwrap_or_else(|| "NULL".to_string());
        sql.push_str(&format!(
            "INSERT INTO parshan (id, name, birth_year, has_pic) VALUES ({}, '{}', {}, {});\n",
            p.id,
            escape_sql(&p.name),
            birth,
            if p.has_pic { 1 } else { 0 }
        ));
    }
    sql.push('\n');
}

fn generate_perushim_sql(sql: &mut String, perushim: &[Perush]) {
    sql.push_str("-- perush\n");
    for p in perushim {
        let comp_date_str = p
            .comp_date
            .as_ref()
            .map(|s| format!("'{}'", escape_sql(s)))
            .unwrap_or_else(|| "NULL".to_string());
        let pub_date_str = p
            .pub_date
            .as_ref()
            .map(|s| format!("'{}'", escape_sql(s)))
            .unwrap_or_else(|| "NULL".to_string());

        sql.push_str(&format!(
            "INSERT INTO perush (id, name, parshan_id, comp_date, pub_date, priority) VALUES ({}, '{}', {}, {}, {}, {});\n",
            p.id,
            escape_sql(&p.name),
            p.parshan_id,
            comp_date_str,
            pub_date_str,
            p.priority
        ));
    }
    sql.push('\n');
}

/// Batch size for multi-row INSERT statements.
/// Keeps each statement well under MySQL's `max_allowed_packet` default (64 MB).
const NOTES_BATCH_SIZE: usize = 500;

fn generate_notes_sql(sql: &mut String, notes: &[Note]) {
    sql.push_str("-- note\n");
    for chunk in notes.chunks(NOTES_BATCH_SIZE) {
        sql.push_str(
            "INSERT INTO note (perush_id, perek_id, pasuk, note_idx, note_content) VALUES\n",
        );
        for (i, n) in chunk.iter().enumerate() {
            if i > 0 {
                sql.push_str(",\n");
            }
            sql.push_str(&format!(
                "({}, {}, {}, {}, '{}')",
                n.perush_id,
                n.perek_id,
                n.pasuk,
                n.note_idx,
                escape_sql(&n.note_content)
            ));
        }
        sql.push_str(";\n");
    }
    sql.push('\n');
}
