name: Continuous Integration

on:
  push:
    branches: master
    paths:
      - web/bible-on-site/**
      - .github/**
  pull_request:
    branches: master
    paths:
      - web/bible-on-site/**
      - .github/**
  workflow_dispatch:
    inputs:
      ref:
        description: 'The branch or tag to run the workflow on'
        required: true
        default: 'master'

jobs:
  build:
    name: Website CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web/bible-on-site
    permissions:
      contents: read

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.ref || github.head_ref }}

      - name: Update PR status
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          curl -L -X POST \
            -H "Authorization: Bearer ${{ secrets.COMMIT_STATUS }}" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -d '{"state": "success", "description": "Workflow completed successfully", "context": "Website CI"}'
            -d '{"state": "success", "description": "Workflow completed successfully", "context": "codecov/project"}'

  
      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: web/bible-on-site/package.json
          cache-dependency-path: web/bible-on-site/package-lock.json
          cache: npm

      - name: Get installed Playwright version
        id: playwright-version
        run: echo "PLAYWRIGHT_VERSION=$(node -e "console.log(require('./package-lock.json').dependencies['@playwright/test'].version)")" >> $GITHUB_ENV

      - name: Cache playwright binaries
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}

      - name: Install npm Dependencies
        id: npm_ci
        run: |
          npm install html-flip-book-react@https://gitpkg.now.sh/doradsoft/html-flip-book/react?master
          npm ci --no-audit

      - name: Install Playwright Dependencies
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: |
          npx playwright install --with-deps
          npx playwright install-deps

      # disabled until prettier config is configured properly
      # - name: Check Format
      #   id: npm-format-check
      #   run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Unit Test
        id: npm-unit-test
        run: npm run test:unit

      - name: Build cache
        uses: actions/cache@v4
        with:
          path: web/bible-on-site/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Build
        id: npm-build
        run: npm run build

      - name: E2E Test
        id: npm-e2e-test
        run: npm run test:e2e

      - name: Merge Test Coverage
        continue-on-error: true
        run: npm run coverage:merge

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: web/bible-on-site/coverage/merged/lcov.info
          disable_search: true

      - name: Perf Test
        id: npm-perf-test
        continue-on-error: true
        run: npm run test:perf

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: web/bible-on-site/playwright-report/
          retention-days: 30
      - name: Update PR status
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -d '{"state": "success", "description": "Workflow completed successfully", "context": "Website CI"}'

