name: Continous Integration

on:
  push:
    branches: master
  pull_request:
    branches: master
  merge_group:
    branches: master
  workflow_dispatch:
    inputs:
      ref:
        description: "The branch or tag to run the workflow on"
        required: true
        default: "master"

env:
  WEBSITE_DIRECTORY: web/bible-on-site
  WEBSITE_NODE_VERSION_FILE: web/bible-on-site/package.json
  WEBSITE_NODE_CACHE_PATH: web/bible-on-site/package-lock.json
  API_DIRECTORY: web/api
  API_CARGO_FILE: web/api/Cargo.toml
  API_TESTS_DIRECTORY: web/api/tests

jobs:
  # ENV SETUP
  setup_env:
    name: Setup Environment Variables
    runs-on: ubuntu-latest
    steps:
      - run: echo "Setting up environment variables"
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.ref || github.head_ref }}
      - name: Get API Playwright version
        id: get_api_playwright_version
        working-directory: ${{ env.API_TESTS_DIRECTORY }}
        run: echo "PLAYWRIGHT_VERSION=$(node -e "console.log(require('./package.json').devDependencies['@playwright/test'])")" >> $GITHUB_OUTPUT
      - name: Get Website Playwright version
        id: get_website_playwright_version
        working-directory: ${{ env.WEBSITE_DIRECTORY }}
        run: echo "PLAYWRIGHT_VERSION=$(node -e "console.log(require('./package.json').devDependencies['@playwright/test'])")" >> $GITHUB_OUTPUT

  # RELEASES
  release_website:
    name: Release Website
    needs: setup_env
    permissions:
      contents: write
      actions: read
    secrets: inherit
    uses: ./.github/workflows/shared-release.yml
    with:
      module_directory: ${{ needs.setup_env.outputs.website_module_dir }}
      version_command: 'npm version patch -m "chore(release): %s [skip ci]"'
      files_to_commit: "package.json package-lock.json"
