name: Continuous Integration

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    name: TypeScript Build
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: web/bible-on-site/package.json
          cache-dependency-path: web/bible-on-site/package-lock.json
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: cd web/bible-on-site && npm ci

      # disabled until prettier config is configured properly
      # - name: Check Format
      #   id: npm-format-check
      #   run: cd web/bible-on-site && npm run format:check

      - name: Lint
        id: npm-lint
        run: cd web/bible-on-site && npm run lint

      - name: Test
        id: npm-unit-test
        run: cd web/bible-on-site && npm run test:unit

      - name: Build
        id: npm-build
        run: cd web/bible-on-site && npm run build
