# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      workflow_to_run:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Workflow to run'
        required: true
        type: choice
        default: 'ci.yml'
        options:
        - 'ci.yml'
      ref:
        description: 'The branch or tag to run the workflow on'
        required: true
        default: 'master'
        # Add other workflow names here

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run_selected_workflow:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Run CI Workflow
        if: ${{ inputs.workflow_to_run == 'CI Workflow' }}
        run: |
          curl -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ github.event.inputs.workflow_name }}/dispatches \
            -d '{"ref":"${{ github.event.inputs.ref }}"}'

        # Add more conditional steps for other workflows
