name: Continous Integration - website

on:
  push:
    branches: master
  pull_request:
    branches: master
  workflow_dispatch:
    inputs:
      ref:
        description: "The branch or tag to run the workflow on"
        required: true
        default: "master"

env:
  MODULE_DIRECTORY: web/bible-on-site
  NODE_VERSION_FILE: web/bible-on-site/package.json
  CACHE_DEPENDENCY_PATH: web/bible-on-site/package-lock.json

jobs:
  # STARTING FLOW
  determine_changes:
    name: Determine Changes
    runs-on: ubuntu-latest
    outputs:
      website_changed: ${{ steps.check_changes.outputs.website_changed }}
      ci_changed: ${{ steps.check_changes.outputs.ci_changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.ref || github.head_ref }}
          fetch-depth: 0

      - name: Check for changes
        id: check_changes
        run: |
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            BASE_SHA=${{ github.event.pull_request.base.sha }}
          else
            BASE_SHA=$(git rev-parse origin/master)
          fi
          WEBSITE_CHANGED=$(git diff --name-only --diff-filter=AM $BASE_SHA HEAD | grep -q "${{ env.MODULE_DIRECTORY }}" && echo "true" || echo "false")
          CI_CHANGED=$(git diff --name-only --diff-filter=AM $BASE_SHA HEAD | grep -q ".github/workflows/website-ci.yml" && echo "true" || echo "false")
          echo "website_changed=${WEBSITE_CHANGED}" >> $GITHUB_OUTPUT
          echo "ci_changed=${CI_CHANGED}" >> $GITHUB_OUTPUT

  # ACTUAL JOBS
  bump-version:
    name: Bump Patch Version
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ${{ env.NODE_VERSION_FILE }}
      - name: Check for changes in ${{ env.MODULE_DIRECTORY }}
        id: paths_filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            bible:
              - '${{ env.MODULE_DIRECTORY }}/**'
      - name: Bump patch version
        if: steps.paths_filter.outputs.bible == 'true'
        run: |
          cd ${{ env.MODULE_DIRECTORY }}
          npm version patch -m "chore(release): %s [skip ci]"
      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
      - name: Add Deploy Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      - name: Commit changes
        if: steps.paths_filter.outputs.bible == 'true'
        run: |
          cd ${{ env.MODULE_DIRECTORY }}
          git add package.json package-lock.json
          git commit -m "chore(release): Bump version [skip ci]"
      - name: Push updated version back to repository
        if: steps.paths_filter.outputs.bible == 'true'
        run: |
          git remote set-url origin git@github.com:${{ github.repository }}
          git push origin HEAD --follow-tags

  performance:
    name: Website Performance
    runs-on: ubuntu-latest
    needs: determine_changes
    if: ${{ needs.determine_changes.outputs.website_changed == 'true' }}
    defaults:
      run:
        working-directory: ${{ env.MODULE_DIRECTORY }}
    permissions:
      contents: read

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.ref || github.head_ref }}

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: ${{ env.NODE_VERSION_FILE }}
          cache-dependency-path: ${{ env.CACHE_DEPENDENCY_PATH }}
          cache: npm

      - name: Get installed Playwright version
        id: playwright-version
        run: echo "PLAYWRIGHT_VERSION=$(node -e "console.log(require('./package.json').devDependencies['@playwright/test'])")" >> $GITHUB_ENV

      - name: Cache playwright binaries
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}

      - name: Install npm Dependencies
        id: npm_ci
        run: |
          npm install html-flip-book-react@https://gitpkg.now.sh/doradsoft/html-flip-book/html-flip-book-react?master
          npm ci --no-audit

      - name: Install Playwright Dependencies
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: |
          npx playwright install --with-deps
          npx playwright install-deps

      - name: Build cache
        uses: actions/cache@v4
        with:
          path: ${{ env.MODULE_DIRECTORY }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Build
        id: npm-build
        run: npm run build

      - name: Perf Test
        id: npm-perf-test
        run: npm run test:perf

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-perf-report
          path: ${{ env.MODULE_DIRECTORY }}/playwright-report/
          retention-days: 30

  end-to-end:
    name: Website CI
    runs-on: ubuntu-latest
    needs: determine_changes
    if: ${{ needs.determine_changes.outputs.website_changed == 'true' || needs.determine_changes.outputs.ci_changed == 'true' }}
    defaults:
      run:
        working-directory: ${{ env.MODULE_DIRECTORY }}
    permissions:
      contents: read

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.ref || github.head_ref }}

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: ${{ env.NODE_VERSION_FILE }}
          cache-dependency-path: ${{ env.CACHE_DEPENDENCY_PATH }}
          cache: npm

      - name: Get installed Playwright version
        id: playwright-version
        run: echo "PLAYWRIGHT_VERSION=$(node -e "console.log(require('./package.json').devDependencies['@playwright/test'])")" >> $GITHUB_ENV

      - name: Cache playwright binaries
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}

      - name: Install npm Dependencies
        id: npm_ci
        run: |
          npm install html-flip-book-react@https://gitpkg.now.sh/doradsoft/html-flip-book/html-flip-book-react?master
          npm ci --no-audit

      - name: Install Playwright Dependencies
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: |
          npx playwright install --with-deps
          npx playwright install-deps

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Unit Test
        id: npm-unit-test
        run: npm run test:unit

      - name: Build cache
        uses: actions/cache@v4
        with:
          path: ${{ env.MODULE_DIRECTORY }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Build
        id: npm-build
        run: npm run build

      - name: E2E Test
        id: npm-e2e-test
        run: npm run test:e2e

      - name: Merge Test Coverage
        continue-on-error: true
        run: npm run coverage:merge

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ${{ env.MODULE_DIRECTORY }}/coverage/merged/lcov.info
          disable_search: true

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ${{ env.MODULE_DIRECTORY }}/coverage/merged/lcov.info

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-e2e-report
          path: ${{ env.MODULE_DIRECTORY }}/playwright-report/
          retention-days: 30

  # CLOSING FLOW
  report_status:
    name: Report Status
    runs-on: ubuntu-latest
    needs: [determine_changes, performance, end-to-end]
    if: always() # This ensures the job always runs
    steps:
      - name: Determine overall status
        id: determine_status
        run: |
          PERFORMANCE_STATUS=$([ "${{ needs.performance.result }}" = "success" ] && echo "success" || echo "failure")
          E2E_STATUS=$([ "${{ needs.end-to-end.result }}" = "success" ] && echo "success" || echo "failure")

          if [ "${{ needs.determine_changes.outputs.website_changed }}" = "true" ] || [ "${{ needs.determine_changes.outputs.ci_changed }}" = "true" ]; then
            # Check Codecov status using the Codecov API
            MAX_RETRIES=10
            RETRY_COUNT=0
            while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
              OWNER_REPO=(${GITHUB_REPOSITORY/\// })
              CODECOV_JSON=$(curl -s -H "Authorization: token ${{ secrets.CODECOV_TOKEN }}" "https://api.codecov.io/api/v2/github/${OWNER_REPO[0]}/repos/${OWNER_REPO[1]}/commits/${{ github.sha }}")
              echo "CODECOV_JSON: $CODECOV_JSON"
              CODECOV_STATUS=$(echo "$CODECOV_JSON" | jq -r '.data.commit.state')
              if [ "$CODECOV_STATUS" = "complete" ]; then
                CODECOV_RESULT=$(echo "$CODECOV_JSON" | jq -r '.data.commit.result')
                if [ "$CODECOV_RESULT" = "error" ]; then
                  echo "Codecov check failed"
                  echo "status=failure" >> $GITHUB_OUTPUT
                  exit 1
                fi
                break
              fi
              echo "Waiting for Codecov status to complete (attempt $((RETRY_COUNT+1))/$MAX_RETRIES)..."
              sleep 30
              RETRY_COUNT=$((RETRY_COUNT+1))
            done
            if [ "$E2E_STATUS" = "failure" ]; then
              echo "Overall status: failure"
              echo "status=failure" >> $GITHUB_OUTPUT
              exit 1
            fi
          fi



          echo "Overall status: success"
          echo "status=success" >> $GITHUB_OUTPUT
